# Local workflow for Angular CLI

name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node-version: [12.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Node $
        uses: actions/setup-node@v1
        with:
          node-version: $

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build:ci